# Generated by Django 3.0.4 on 2020-03-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turtorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turtorial_title', models.CharField(max_length=200)),
                ('turtorial_content', models.TextField()),
                ('turtorial_published', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
