# Generated by Django 3.0.4 on 2020-03-27 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Turtorial',
            new_name='Tutorial',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='turtorial_content',
            new_name='tutorial_content',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='turtorial_published',
            new_name='tutorial_published',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='turtorial_title',
            new_name='tutorial_title',
        ),
    ]
