# Generated by Django 3.0.4 on 2020-03-27 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200327_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 27, 19, 33, 53, 557664), verbose_name='date published'),
        ),
    ]
