# Generated by Django 2.1.5 on 2020-05-09 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200509_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 15, 58, 22, 331884), verbose_name='date published'),
        ),
    ]
